version: '3.7'

volumes:
  pgvol_meal:
  pgadmin_meal: 

services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    container_name: 'pgadmin-meal'
    ports:
      - '7300:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_meal:/var/lib/pgadmin
    networks:
      meal-app:
        ipv4_address: 57.0.0.2
  postgres:
    restart: always
    image: postgres
    container_name: 'postgres-meal'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mealuser
      POSTGRES_PASSWORD: mealpassword
      POSTGRES_DB: meal_db
    volumes:
      - pgvol_meal:/var/lib/postgresql/data
    networks:
      meal-app:
          ipv4_address: 57.0.0.3
  redis:
    build: 
      context: ./redis
      dockerfile: ./Dockerfile
    container_name: db-redis
    command: bash -c "redis-server --bind 57.0.0.4"
    ports:
      - "6379:6379"
    networks:
      meal-app:
        ipv4_address: 57.0.0.4

networks:
  meal-app:
    driver: bridge
    ipam:
      config:
        - subnet: 57.0.0.0/24