# Generated by Django 3.0.3 on 2020-06-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('worker', 'date')},
        ),
    ]
