# Generated by Django 3.0.3 on 2020-06-04 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manager', '0002_auto_20200603_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
