# Generated by Django 3.0.3 on 2020-06-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manager', '0002_auto_20200601_2352'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('menu', 'name')},
        ),
    ]
