# Generated by Django 3.0.3 on 2020-06-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manager', '0003_worker_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='unique_id',
            new_name='unique_uuid',
        ),
    ]
